spring.application.name=stock

server.port=8080

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:~/db/stockmanagement;MODE=MySQL
spring.datasource.username=sa
spring.datasource.password=1234

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.check-template-location=true
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.thymeleaf.prefix=classpath:/templates/

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

paging.pageNumber-limit=10
paging.pageItem-limit=10

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.max-file-size=50MB

# ?? ?? ?? (??? ??, ??? ??? ???? ??? ???)
com.example.upload.path=C:\\upload
spring.servlet.multipart.location=C:/upload/temp

# 1. ??? ???? ?? ??? ?? (??? 2MB)
# -1? ???? ??????. (???? ?? ??? ??)
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1

